### ISSUE TITLE
Is it possible to animate a line graph?

### ISSUE THREAD

**Issue by BigPun86** [tomauty/react-native-chart#130]
Hey there, is it possible to animate the line chart, when the chartData has changed? 

I want to display a line chart which has three different datas. When i click a button for example the linegraph should animate to the next chartData array...

Any hints? :P

**Comment by tomauty** [comment]
Hello. I'm actually working behind the scenes to transition this project to use react-native-svg instead of react-native ART objects. SVG transforms are supported in RN SVG, but I don't have much experience with it. 

You can make the line chart animate such that it grows from the bottom, in the meantime. If you're interested I can post a snippet.

**Comment by em222iv** [comment]
I would appreciate if you could post a snippet of the animation code, please!

**Comment by Crash--** [comment]
@tomauty Is there a way to help you with the migration?

**Comment by tomauty** [comment]
Yes! I'm really sorry for not maintaining properly, swamped with work right now. The branch is `react-native-svg`, and so far only the LineChart supports it. Would love any PRs that convert the bar chart or pie chart to use SVG objects.
